// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_REQUEST_LRUCACHE_SCHEMA_H_
#define FLATBUFFERS_GENERATED_REQUEST_LRUCACHE_SCHEMA_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 23 &&
              FLATBUFFERS_VERSION_MINOR == 5 &&
              FLATBUFFERS_VERSION_REVISION == 26,
             "Non-compatible flatbuffers version included");

#include "DiscoveryRequest_generated.h"

namespace lrucache {
namespace schema {

struct Request;
struct RequestBuilder;

enum RequestContent : uint8_t {
  RequestContent_NONE = 0,
  RequestContent_DiscoveryRequest = 1,
  RequestContent_MIN = RequestContent_NONE,
  RequestContent_MAX = RequestContent_DiscoveryRequest
};

inline const RequestContent (&EnumValuesRequestContent())[2] {
  static const RequestContent values[] = {
    RequestContent_NONE,
    RequestContent_DiscoveryRequest
  };
  return values;
}

inline const char * const *EnumNamesRequestContent() {
  static const char * const names[3] = {
    "NONE",
    "DiscoveryRequest",
    nullptr
  };
  return names;
}

inline const char *EnumNameRequestContent(RequestContent e) {
  if (::flatbuffers::IsOutRange(e, RequestContent_NONE, RequestContent_DiscoveryRequest)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesRequestContent()[index];
}

template<typename T> struct RequestContentTraits {
  static const RequestContent enum_value = RequestContent_NONE;
};

template<> struct RequestContentTraits<lrucache::schema::DiscoveryRequest> {
  static const RequestContent enum_value = RequestContent_DiscoveryRequest;
};

bool VerifyRequestContent(::flatbuffers::Verifier &verifier, const void *obj, RequestContent type);
bool VerifyRequestContentVector(::flatbuffers::Verifier &verifier, const ::flatbuffers::Vector<::flatbuffers::Offset<void>> *values, const ::flatbuffers::Vector<uint8_t> *types);

struct Request FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef RequestBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_CONTENT_TYPE = 4,
    VT_CONTENT = 6
  };
  lrucache::schema::RequestContent content_type() const {
    return static_cast<lrucache::schema::RequestContent>(GetField<uint8_t>(VT_CONTENT_TYPE, 0));
  }
  const void *content() const {
    return GetPointer<const void *>(VT_CONTENT);
  }
  template<typename T> const T *content_as() const;
  const lrucache::schema::DiscoveryRequest *content_as_DiscoveryRequest() const {
    return content_type() == lrucache::schema::RequestContent_DiscoveryRequest ? static_cast<const lrucache::schema::DiscoveryRequest *>(content()) : nullptr;
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint8_t>(verifier, VT_CONTENT_TYPE, 1) &&
           VerifyOffset(verifier, VT_CONTENT) &&
           VerifyRequestContent(verifier, content(), content_type()) &&
           verifier.EndTable();
  }
};

template<> inline const lrucache::schema::DiscoveryRequest *Request::content_as<lrucache::schema::DiscoveryRequest>() const {
  return content_as_DiscoveryRequest();
}

struct RequestBuilder {
  typedef Request Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_content_type(lrucache::schema::RequestContent content_type) {
    fbb_.AddElement<uint8_t>(Request::VT_CONTENT_TYPE, static_cast<uint8_t>(content_type), 0);
  }
  void add_content(::flatbuffers::Offset<void> content) {
    fbb_.AddOffset(Request::VT_CONTENT, content);
  }
  explicit RequestBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<Request> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<Request>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<Request> CreateRequest(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    lrucache::schema::RequestContent content_type = lrucache::schema::RequestContent_NONE,
    ::flatbuffers::Offset<void> content = 0) {
  RequestBuilder builder_(_fbb);
  builder_.add_content(content);
  builder_.add_content_type(content_type);
  return builder_.Finish();
}

inline bool VerifyRequestContent(::flatbuffers::Verifier &verifier, const void *obj, RequestContent type) {
  switch (type) {
    case RequestContent_NONE: {
      return true;
    }
    case RequestContent_DiscoveryRequest: {
      auto ptr = reinterpret_cast<const lrucache::schema::DiscoveryRequest *>(obj);
      return verifier.VerifyTable(ptr);
    }
    default: return true;
  }
}

inline bool VerifyRequestContentVector(::flatbuffers::Verifier &verifier, const ::flatbuffers::Vector<::flatbuffers::Offset<void>> *values, const ::flatbuffers::Vector<uint8_t> *types) {
  if (!values || !types) return !values && !types;
  if (values->size() != types->size()) return false;
  for (::flatbuffers::uoffset_t i = 0; i < values->size(); ++i) {
    if (!VerifyRequestContent(
        verifier,  values->Get(i), types->GetEnum<RequestContent>(i))) {
      return false;
    }
  }
  return true;
}

inline const lrucache::schema::Request *GetRequest(const void *buf) {
  return ::flatbuffers::GetRoot<lrucache::schema::Request>(buf);
}

inline const lrucache::schema::Request *GetSizePrefixedRequest(const void *buf) {
  return ::flatbuffers::GetSizePrefixedRoot<lrucache::schema::Request>(buf);
}

inline bool VerifyRequestBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<lrucache::schema::Request>(nullptr);
}

inline bool VerifySizePrefixedRequestBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<lrucache::schema::Request>(nullptr);
}

inline void FinishRequestBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<lrucache::schema::Request> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedRequestBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<lrucache::schema::Request> root) {
  fbb.FinishSizePrefixed(root);
}

}  // namespace schema
}  // namespace lrucache

#endif  // FLATBUFFERS_GENERATED_REQUEST_LRUCACHE_SCHEMA_H_
